export const PersonalDataExample = [
  {
    id: 1,
    name: "Aleksander",
    secondName: "Aleksandrovich",
    surname: "Koryakin",
    post: "laserboy",
    salary: 500,
  },
  {
    id: 2,
    name: "Aleksei",
    secondName: "Petrovich",
    surname: "Bubyakin",
    post: "svarka",
    salary: 600,
  },
  {
    id: 3,
    name: "Viktor",
    secondName: "Olegovich",
    surname: "Ivanov",
    post: "svarka",
    salary: 600,
  },
  {
    id: 4,
    name: "Aleksander",
    secondName: "Pavlovich",
    surname: "Tryetyakov",
    post: "Painter",
    salary: 550,
  },
  {
    id: 5,
    name: "Evgeny",
    secondName: "Alekseevich",
    surname: "Petrov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 6,
    name: "Artem",
    secondName: "Artemovich",
    surname: "Artemov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 7,
    name: "Aleksander",
    secondName: "Aleksandrovich",
    surname: "Koryakin",
    post: "laserboy",
    salary: 500,
  },
  {
    id: 8,
    name: "Aleksei",
    secondName: "Petrovich",
    surname: "Bubyakin",
    post: "svarka",
    salary: 600,
  },
  {
    id: 9,
    name: "Viktor",
    secondName: "Olegovich",
    surname: "Ivanov",
    post: "svarka",
    salary: 600,
  },
  {
    id: 10,
    name: "Aleksander",
    secondName: "Pavlovich",
    surname: "Tryetyakov",
    post: "Painter",
    salary: 550,
  },
  {
    id: 11,
    name: "Evgeny",
    secondName: "Alekseevich",
    surname: "Petrov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 12,
    name: "Artem",
    secondName: "Artemovich",
    surname: "Artemov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 13,
    name: "Aleksander",
    secondName: "Aleksandrovich",
    surname: "Koryakin",
    post: "laserboy",
    salary: 500,
  },
  {
    id: 14,
    name: "Aleksei",
    secondName: "Petrovich",
    surname: "Bubyakin",
    post: "svarka",
    salary: 600,
  },
  {
    id: 15,
    name: "Viktor",
    secondName: "Olegovich",
    surname: "Ivanov",
    post: "svarka",
    salary: 600,
  },
  {
    id: 16,
    name: "Aleksander",
    secondName: "Pavlovich",
    surname: "Tryetyakov",
    post: "Painter",
    salary: 550,
  },
  {
    id: 17,
    name: "Evgeny",
    secondName: "Alekseevich",
    surname: "Petrov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 18,
    name: "Artem",
    secondName: "Artemovich",
    surname: "Artemov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 19,
    name: "Aleksander",
    secondName: "Aleksandrovich",
    surname: "Koryakin",
    post: "laserboy",
    salary: 500,
  },
  {
    id: 20,
    name: "Aleksei",
    secondName: "Petrovich",
    surname: "Bubyakin",
    post: "svarka",
    salary: 600,
  },
  {
    id: 21,
    name: "Viktor",
    secondName: "Olegovich",
    surname: "Ivanov",
    post: "svarka",
    salary: 600,
  },
  {
    id: 22,
    name: "Aleksander",
    secondName: "Pavlovich",
    surname: "Tryetyakov",
    post: "Painter",
    salary: 550,
  },
  {
    id: 23,
    name: "Evgeny",
    secondName: "Alekseevich",
    surname: "Petrov",
    post: "chpuOperator",
    salary: 800,
  },
  {
    id: 24,
    name: "Artem",
    secondName: "Artemovich",
    surname: "Artemov",
    post: "chpuOperator",
    salary: 800,
  },
];
